services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ctw-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - FORCE_COLOR=1
    command: ["pnpm", "dev", "--", "--host", "0.0.0.0"]
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ctw-backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: ["pnpm", "dev"]
    tty: true